### ISSUE TITLE
Change the title of 'Custom Product Types' to Categories in admin

### ISSUE THREAD

**Issue by christianc1** [LiftUX/flag-loft-custom-products#3]
https://github.com/LiftUX/flagloft/issues/59

**Comment by christianc1** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;qGdddEtG&#x2F;1-change-admin-labels-for-custom-product-types"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Change Admin Labels for Custom Product Types</a>

**Comment by angela-crist** [comment]
Thanks! Looks great http://lift.d.pr/1jRuI/2y6MtUDS
